# Generated by Django 5.1.6 on 2025-03-02 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0002_store'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
