# Generated by Django 5.1.6 on 2025-03-01 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TripLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_address', models.CharField(max_length=255)),
                ('source_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('source_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('destination_address', models.CharField(max_length=255)),
                ('dest_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('dest_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('mode_of_transport', models.CharField(max_length=50)),
                ('time_taken', models.FloatField()),
                ('api_duration', models.FloatField()),
                ('api_distance', models.FloatField()),
                ('electric_vehicle', models.BooleanField(default=False)),
                ('co2_emission', models.FloatField()),
                ('date', models.DateField()),
                ('passengers', models.IntegerField(default=1)),
                ('public_transport', models.BooleanField(default=False)),
                ('greener_travel', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
